### PR TITLE
calling the factory method with pre-populated YAML

### PR DESCRIPTION
**Pull request by marc-hanheide**
to allows task to know these values already, so they can be instantiated taking them into account.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@cdondrup will be happy about this... You can now use the `start_after`, `end_before`, `start_node_id` and `end_node_id` already at creation time. You should not always trust these values to be set (other routines might not set it), but if they are set, they are meaningful and gcal sets them now.

**Comment by marc-hanheide** [comment]
@cdondrup could you test this in the context of walking_group maybe?

**Comment by marc-hanheide** [comment]
Why is the fifo_test still in @hawesie ?

**Comment by hawesie** [comment]
Maybe you didn't rebase? Or someone added it back in somehow? It wasn't purposeful.

**Comment by marc-hanheide** [comment]
it's strange... as you see it's not in the changes (so I rebased correctly), and it's not in upstream either. That's why I was wondering...

**Comment by marc-hanheide** [comment]
retest this please

**Pull request merged**
