### PR TITLE
Moving recent changes to release.

### PR DESCRIPTION
**Pull request by hawesie**

### CODE REVIEW

**Comment by hawesie** [comment]
This needs a new release of strands_navigation.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
another magic phrase that jenkins understands ;-)

**Comment by marc-hanheide** [comment]
something still wrong with the test: http://lcas.lincoln.ac.uk/jenkins/job/pr-hydro-strands_executive/20/testReport/(root)/Results/test_ran/

```
Error Message

Unable to find test results for rostest-tests_fifo_tester.xml, test did not run. Expected results in /var/lib/jenkins/workspace/pr-hydro-strands_executive/test_results/repos/task_executor/rostest-tests_fifo_tester.xml
```

**Comment by hawesie** [comment]
This is the error:

```
roslaunch.core.RLException: while processing /opt/ros/hydro/share/mongodb_store/launch/mongodb_store.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/opt/ros/hydro/share/mongodb_store/launch/mongodb_store.launch'
```

Fixing this with a new release of `mongodb_store`.

**Comment by marc-hanheide** [comment]
Ah, I see. Can people also make sure they commit with their git email configured correctly on their computers: @mudrole1  and @BFALacerda  both commit with some invalid email addresses all the time:

```
Invalid address: lenka@Thinker-Lenka.(none)
Invalid address: bruno@bruno-dell.(none)
```

Please refer to https://help.github.com/articles/setting-your-email-in-git/
Best practice: Put your github-registered address there.
It's not a biggy, just I get all the complaints from the server about mail delivery failures.

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
retest this please and really please work this time (@marc-hanheide, how is the Jenkins command matched?)

**Comment by hawesie** [comment]
FINALLY!

**Pull request merged**
