### PR TITLE
streamlining nav pipeline

### PR DESCRIPTION
**Pull request by bfalacerda**
this makes the execution of navigation policies less buggy

### CODE REVIEW

**Comment by marc-hanheide** [comment]
test this please

**Comment by marc-hanheide** [comment]
ok, `topological_navigation` is still not released... will have to wait a bit longer

**Comment by marc-hanheide** [comment]
so, now it is released, so test this please

**Comment by marc-hanheide** [comment]
now dateutil is available so test this please

**Comment by marc-hanheide** [comment]
another one:

```
[ 13%] Performing update step for 'Prism'
PRISM was unable to find the directory which contains
your Java distribution. Please specify this manually to
make, as in these examples:

  make JAVA_DIR=/usr/java/j2sdk1.4.2
  make JAVA_DIR="/cygdrive/c/Program Files/Java/jdk1.4.2"

See the PRISM manual for further information.
```

**Comment by hawesie** [comment]
@BFALacerda are we going to use these updates for the marathon?

**Comment by bfalacerda** [comment]
If the plan is only using released code, then I don't think so, I'm still not sure on what to do with PRISM

**Comment by marc-hanheide** [comment]
May I then suggest you maintain this in a separate branch for now?

**Comment by marc-hanheide** [comment]
and close this PR?

**Comment by bfalacerda** [comment]
That also requires changes to be done on the scheduler and on the executor. I thought that's why we created the hydro-release branch

**Comment by marc-hanheide** [comment]
Ah... I didn't know about that. OK then we need to check if the release is based on the right branch

**Comment by marc-hanheide** [comment]
so, ok the releases are based on the `hydro-release` branch. so that's all good. You still want to fix this devel build I suppose before merging it (i.e. fix the java problem)?

**Comment by bfalacerda** [comment]
yes, any suggestions on how to do it?

For the release I was thinking of having PRISM as a debian package of its own, add it to our package releases, and just add it as a dependency of the mdp_plan_exec ROS package. Can you list what needs to be done in order to release a non-ROS package to the STRANDS repository? @marc-hanheide

**Comment by marc-hanheide** [comment]
What is prism? Is there probably a PPA with a package already existing? Is it java? Have you got a link for me?

**Comment by bfalacerda** [comment]
PRISM is the software we use to generate policies for the robots. It's homepage is here:

http://www.prismmodelchecker.org/

the only way to install it now is getting the source code and compiling. The source code we are using is here:

https://github.com/BFALacerda/prism-robots

**Comment by hawesie** [comment]
I think we should just merge this into devel regardless of what Jenkins says. Builds here will keep failing until we've fixed a bunch of problems that are beyond this PR.

**Pull request merged**
