### PR TITLE
changes to handle concurrency

### PR DESCRIPTION
**Pull request by bfalacerda**
and a couple of small bug fixes
tested on Bob, looks like its working. more tests tomorrow
Requires prism update and recompilation

### CODE REVIEW

**Comment by hawesie** [comment]
Which are the actual commits of relevance? There seems to be a lot of extra old things here? Also, you need to set up git wherever you're working so it correctly links commits to your account (not for this request though).

**Comment by bfalacerda** [comment]
it's just the last 4, if you look at the files changes all the rest is the same.

 I don't know why github still shows such a big list

**Comment by hawesie** [comment]
Please can you create a new branch from master then cherry pick in the last 4 commits for a new pull request? I'm a bit nervous about (re)merging all that history.

**Comment by hawesie** [comment]
I'd like to play with this, so I will do this in the next 20 minutes unless you shout otherwise @BFALacerda

**Comment by hawesie** [comment]
Now reopened over at #68

**Pull request closed without merging**
