### PR TITLE
download prism-svn

### PR DESCRIPTION
**Pull request by bfalacerda**
i'm doing something wrong here, it doesn't compile. I get:

```
make[3]: warning: jobserver unavailable: using -j1. Add `+' to parent make rule.
rsync: link_stat "/home/bruno/devel_ws/build/prism_strands/prism/src/prism/prism/classes" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
make[2]: *** [prism/src/prism-stamp/prism-install] Error 23
make[1]: *** [CMakeFiles/prism.dir/all] Error 2
make: *** [all] Error 2
```

### CODE REVIEW

**Comment by bfalacerda** [comment]
@marc-hanheide can  you help me?

**Comment by marc-hanheide** [comment]
Compilation worked. This is the install step. Apparently, your version doesn't create the `classes` directory. Something the latest version did... What parts need to be part of the installation is the question. Somebody should really provide prism with a proper installation rule...

**Comment by bfalacerda** [comment]
i made it compile properly and updated the code to work with running prism using rosrun. @marc-hanheide is it ok to merge?

**Comment by marc-hanheide** [comment]
Did you test this also with `catkin_make_isolated --install` to see if it all ends up in the right place an works?

**Comment by bfalacerda** [comment]
nop, i just used catkin build. i'll try on a clean ws and let you know.

**Comment by bfalacerda** [comment]
ok, tested with catkin_make_isolated --install and everything seems alright.

**Pull request merged**
