### PR TITLE
Fixing the issue that drop method should work with all tasks, even though previously scheduled

### PR DESCRIPTION
**Pull request by mudrole1**

### CODE REVIEW

**Comment by hawesie** [comment]
Could you write a bit of an explanation of why the change was needed and/or what it does. Also, I guess @marc-hanheide or someone with the AAF team needs to test.

**Comment by marc-hanheide** [comment]
We discussed on gitter. @cdondrup and I shall test.

**Comment by mudrole1** [comment]
Summary: 
-the scheduler is called with tasks containing old ones (previously scheduled) and new ones. If it doesnt find a solution, then method drop choose which task to drop from those sets. The method drop was written correctly, assuming all task, I was just passing wrong set - not all tasks, but only the new ones (this was some older behaviour).

However, as the method drop practicaly mix old ones and new ones, and can cancel even old one, I needed to ad quite a lot of code to ensure, that correct tasks are passed to executor. This means remove old tasks which are in "throwen_away" set from the execution queue. Moreover, from set called "additional_tasks" (stupid name, contains all tasks which should be executed = old and new ones) take only the newly added - add them to the execution queue and set the schedule.

**Comment by marc-hanheide** [comment]
So far, this appears to be working as expected for us. We'll run a bit longer, but looks good so far.

**Comment by cdondrup** [comment]
here is my current experience. The infor terminal is running and schedules up to 5 tasks with priority 1 every 5 minutes. The current schedule looks like this:

```
currently_executing: False
execution_queue: 
  - 
    task_id: 28
    start_node_id: ChargingPoint
    end_node_id: ChargingPoint
    action: /info_task_server
    start_after: 
      secs: 1431187805
      nsecs: 0
    end_before: 
      secs: 1431188098
      nsecs: 0
    max_duration: 
      secs: 180
      nsecs: 0
    execution_time: 
      secs: 1431187805
      nsecs: 0
    priority: 1
    arguments: []
  - 
    task_id: 31
    start_node_id: WayPoint5
    end_node_id: WayPoint5
    action: /info_task_server
    start_after: 
      secs: 1431188105
      nsecs: 0
    end_before: 
      secs: 1431188398
      nsecs: 0
    max_duration: 
      secs: 180
      nsecs: 0
    execution_time: 
      secs: 1431188105
      nsecs: 0
    priority: 1
    arguments: []
  - 
    task_id: 34
    start_node_id: WayPoint5
    end_node_id: WayPoint5
    action: /info_task_server
    start_after: 
      secs: 1431188405
      nsecs: 0
    end_before: 
      secs: 1431188698
      nsecs: 0
    max_duration: 
      secs: 290
      nsecs: 0
    execution_time: 
      secs: 1431188405
      nsecs: 0
    priority: 1
    arguments: []
```

Now when I schedule a task with priority 2:

```
[INFO] [WallTime: 1431187433.072982] updating from google calendar https://www.googleapis.com/calendar/v3/calendars/hanheide.net_6hgulf44ij7ctjrf2iscj0m24o@group.calendar.google.com/events?key=AIzaSyC1rqV2yecWwV0
eLgmoQH7m7PdLNX1p6a0&singleEvents=true&orderBy=startTime&maxResults=2500&timeMin=2015-05-08T17:03:53.072653Z&timeMax=2015-05-11T17:03:53.072653Z
[INFO] [WallTime: 1431187433.237092] changes in the calendar to process +1 -1
[INFO] [WallTime: 1431187433.238371] instantiate 18813gi38eg9rg0rvedok4e25k2015-05-09T16:03:29.378Z
[INFO] [WallTime: 1431187433.240799] calling with pre-populated yaml: {start_after: {secs: 1431187500, nsecs: 0}, end_before: {secs: 1431192300, nsecs: 0}, start_node_id: 'WayPoint9', end_node_id: 'WayPoint9'}
[INFO] [WallTime: 1431187433.251267] got the task back: task_id: 0
start_node_id: WayPoint9
end_node_id: WayPoint9
action: walking_group_fast
start_after: 
  secs: 1431187500
  nsecs: 0
end_before: 
  secs: 1431192300
  nsecs: 0
max_duration: 
  secs: 4800
  nsecs: 0
execution_time: 
  secs: 0
  nsecs: 0
priority: 3
arguments: []
[INFO] [WallTime: 1431187433.252510] adding 18813gi38eg9rg0rvedok4e25k2015-05-09T16:03:29.378Z to the waiting queue. Now we have 1 tasks in the waiting queue.
[WARN] [WallTime: 1431187433.253526] task 18813gi38eg9rg0rvedok4e25k2015-05-09T15:57:49.230Z to be deleted was not in the waiting set. It may be from the past
[INFO] [WallTime: 1431187433.710632] task 18813gi38eg9rg0rvedok4e25k2015-05-09T16:03:29.378Z to start after 2015-05-09 17:05:00  1431187500 should be scheduled now.
[INFO] [WallTime: 1431187433.711997] removing 18813gi38eg9rg0rvedok4e25k2015-05-09T16:03:29.378Z from the waiting queue. Now we have 0 tasks in the waiting queue.
[INFO] [WallTime: 1431187433.716636] setting priority of tasks to 2
[INFO] [WallTime: 1431187433.717761] Sending 1 tasks to the scheduler
[INFO] [WallTime: 1431187433.726905] Got a further 1 tasks to schedule
[INFO] [WallTime: 1431187433.804128] The specification is R{"time"}min=? [ ( F "ChargingPoint") ]
received: get_vector
[INFO] [WallTime: 1431187433.820184] Expected times to target state: [0.0, 31.349629026, 66.42971645042866, 69.4613042185111, 40.17280965843592, 56.10845355553032, 68.07604671747717, 56.07161313368348, 63.848862728090964, 46.73939370173442, 41.005135547553266, 36.220454114]
[INFO] [WallTime: 1431187433.933143] The specification is R{"time"}min=? [ ( F "WayPoint5") ]
received: get_vector
[INFO] [WallTime: 1431187433.950349] Expected times to target state: [53.90301100966245, 30.175972042722158, 18.254143266285393, 19.64990045, 22.860199437065905, 7.932878744, 12.004433588079687, 0.0, 14.03745821$, 12.234737301518319, 39.83147419026106, 30.27563314481657]
[INFO] [WallTime: 1431187434.025830] The specification is R{"time"}min=? [ ( F "WayPoint5") ]
received: get_vector
[INFO] [WallTime: 1431187434.042858] Expected times to target state: [53.90301100966245, 30.175972042722158, 18.254143266285393, 19.64990045, 22.860199437065905, 7.932878744, 12.004433588079687, 0.0, 14.03745821$, 12.234737301518319, 39.83147419026106, 30.27563314481657]
[INFO] [WallTime: 1431187434.087850] The specification is R{"time"}min=? [ ( F "WayPoint9") ]
received: get_vector
[INFO] [WallTime: 1431187434.107179] Expected times to target state: [29.43163145504697, 5.704592488, 40.78468082907955, 43.81626818656443, 14.527773120430236, 30.46341702294025, 42.43101018146809, 30.42657659569
0033, 38.203826242436264, 21.094357163728738, 15.360099173669756, 0.0]
[ INFO] [1431187434.114579767]: SCHEDULER: Got a request for a schedule 4 tasks 
[ INFO] [1431187434.133367467]: SCHEDULER: Going to solve
[ INFO] [1431187434.136803998]: SCHEDULER: The input problem had a flaw, scheduler didnt attempt

[INFO] [WallTime: 1431187434.137155] No schedule found
[INFO] [WallTime: 1431187434.138463] Schedule not found, trying to discard 1 tasks with priority 1
[INFO] [WallTime: 1431187434.143512] The specification is R{"time"}min=? [ ( F "WayPoint9") ]
received: get_vector
[INFO] [WallTime: 1431187434.155680] Expected times to target state: [29.43163145504697, 5.704592488, 40.78468082907955, 43.81626818656443, 14.527773120430236, 30.46341702294025, 42.43101018146809, 30.42657659569
0033, 38.203826242436264, 21.094357163728738, 15.360099173669756, 0.0]
[INFO] [WallTime: 1431187434.177677] The specification is R{"time"}min=? [ ( F "ChargingPoint") ]
received: get_vector
[INFO] [WallTime: 1431187434.196447] Expected times to target state: [0.0, 31.349629026, 66.42971645042866, 69.4613042185111, 40.17280965843592, 56.10845355553032, 68.07604671747717, 56.07161313368348, 63.8488627
28090964, 46.73939370173442, 41.005135547553266, 36.220454114]
[INFO] [WallTime: 1431187434.273307] The specification is R{"time"}min=? [ ( F "WayPoint5") ]
received: get_vector
[INFO] [WallTime: 1431187434.292262] Expected times to target state: [53.90301100966245, 30.175972042722158, 18.254143266285393, 19.64990045, 22.860199437065905, 7.932878744, 12.004433588079687, 0.0, 14.037458211
, 12.234737301518319, 39.83147419026106, 30.27563314481657]
[ INFO] [1431187434.298323905]: SCHEDULER: Got a request for a schedule 3 tasks 
[ INFO] [1431187434.315537677]: SCHEDULER: Going to solve
[ INFO] [1431187434.319525019]: SCHEDULER: The input problem had a flaw, scheduler didnt attempt

[INFO] [WallTime: 1431187434.319809] No schedule found
[INFO] [WallTime: 1431187434.321624] Schedule not found, trying to discard 1 tasks with priority 1
[INFO] [WallTime: 1431187434.364554] The specification is R{"time"}min=? [ ( F "WayPoint9") ]
received: get_vector
[INFO] [WallTime: 1431187434.387880] Expected times to target state: [29.43163145504697, 5.704592488, 40.78468082907955, 43.81626818656443, 14.527773120430236, 30.46341702294025, 42.43101018146809, 30.42657659569
0033, 38.203826242436264, 21.094357163728738, 15.360099173669756, 0.0]
[INFO] [WallTime: 1431187434.417182] The specification is R{"time"}min=? [ ( F "ChargingPoint") ]
received: get_vector
[INFO] [WallTime: 1431187434.439619] Expected times to target state: [0.0, 31.349629026, 66.42971645042866, 69.4613042185111, 40.17280965843592, 56.10845355553032, 68.07604671747717, 56.07161313368348, 63.8488627
28090964, 46.73939370173442, 41.005135547553266, 36.220454114]
[ INFO] [1431187434.445659251]: SCHEDULER: Got a request for a schedule 2 tasks 
[ INFO] [1431187434.459463334]: SCHEDULER: Going to solve
[ INFO] [1431187434.462283742]: SCHEDULER: The input problem had a flaw, scheduler didnt attempt

[INFO] [WallTime: 1431187434.462555] No schedule found
[INFO] [WallTime: 1431187434.463495] Schedule not found, trying to discard 1 tasks with priority 1
[INFO] [WallTime: 1431187434.504504] The specification is R{"time"}min=? [ ( F "WayPoint9") ]
received: get_vector
[INFO] [WallTime: 1431187434.527363] Expected times to target state: [29.43163145504697, 5.704592488, 40.78468082907955, 43.81626818656443, 14.527773120430236, 30.46341702294025, 42.43101018146809, 30.42657659569
0033, 38.203826242436264, 21.094357163728738, 15.360099173669756, 0.0]
[ INFO] [1431187434.531962032]: SCHEDULER: Got a request for a schedule 1 tasks 
[ INFO] [1431187434.539314058]: SCHEDULER: Going to solve
[ INFO] [1431187434.553962183]: SCHEDULER: found a solution
[WARN] [WallTime: 1431187434.554574] Number of scheduled tasks mismatch: given 1, had 3
[INFO] [WallTime: 1431187434.555965] Added 1 tasks into the schedule to get total of 2
```

After which the current schedule looks like this:

```
currently_executing: False
execution_queue: 
  - 
    task_id: 31
    start_node_id: WayPoint5
    end_node_id: WayPoint5
    action: /info_task_server
    start_after: 
      secs: 1431188105
      nsecs: 0
    end_before: 
      secs: 1431188398
      nsecs: 0
    max_duration: 
      secs: 180
      nsecs: 0
    execution_time: 
      secs: 1431188105
      nsecs: 0
    priority: 1
    arguments: []
  - 
    task_id: 34
    start_node_id: WayPoint5
    end_node_id: WayPoint5
    action: /info_task_server
    start_after: 
      secs: 1431188405
      nsecs: 0
    end_before: 
      secs: 1431188698
      nsecs: 0
    max_duration: 
      secs: 290
      nsecs: 0
    execution_time: 
      secs: 1431188405
      nsecs: 0
    priority: 1
    arguments: []
---
```

So apparently it dropped task 28 but that wasn't enough to fit my task in. Why didn't it drop the others? @mudrole1 any idea?

**Comment by cdondrup** [comment]
Works fine if no other tasks are in the current schedule.

**Comment by mudrole1** [comment]
Ok, I was not correctly deleting the throwen tasks, now it is fixed and should finally work :-/ I will have look on the bug from gitter now

**Comment by cdondrup** [comment]
This seems to work as expected now except for #204 which might be unrelated, but makes testing quite hard.

**Comment by hawesie** [comment]
#204 I think is @mudrole1's too.

**Comment by mudrole1** [comment]
This should be ready now...finger cross! :) I created a new test num. 12 in "test_priorities.py" to simulate this situation.

**Comment by hawesie** [comment]
retest please

**Comment by marc-hanheide** [comment]
retest this please

**Comment by cdondrup** [comment]
This seems to work for me in simulation. I'd say we try to run our whole system with this tomorrow at aaf and if that works it should be merged imho.

**Comment by hawesie** [comment]
cool

**Comment by cdondrup** [comment]
This seems to work now. Please merge and re-release if possible. Thank you for your help @mudrole1 !

**Pull request merged**
