### PR TITLE
Routine analysis tools

### PR DESCRIPTION
**Pull request by hawesie**
This merges in the routine analysis tools as used at the Y2 review.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
This contains a bit more than just the analysis stuff...

**Comment by hawesie** [comment]
AH poop. It's only that first commit. And that adds an extra node which doesn't have to be run.

**Comment by marc-hanheide** [comment]
Yes, but it also changes the default launch files being used by everybody?

**Comment by hawesie** [comment]
The launch file changes are now at https://github.com/hawesie/strands_executive/tree/node_relax_node

**Comment by hawesie** [comment]
@marc-hanheide if builds ok, can we merge?

**Comment by hawesie** [comment]
retest please

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
@hawesie needs to be more polite for Jenkins to obey 😉

**Comment by hawesie** [comment]
@marc-hanheide 

```
W: Failed to fetch bzip2:/var/lib/apt/lists/partial/us.archive.ubuntu.com_ubuntu_dists_trusty-updates_main_i18n_Translation-en  Hash Sum mismatch
```

**Comment by marc-hanheide** [comment]
means they have updated the file between us loading the index and them updating the file...

**Comment by hawesie** [comment]
Can we reload?

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
every build is a fresh install, so re-testing will reload the index

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
something is odd with Jenkins. these test pass locally.

**Comment by marc-hanheide** [comment]
the test still fails:

```
[task_executor.rosunit-scheduled_exe_tester/test_fifo_task_executor][FAILURE]---
Lists differ: [['h_1', 'test_task_1', 'oh wh... != []

First list contains 1 additional elements.
First extra element 0:
['h_1', 'test_task_1', 'oh what a lovely number 4 is', position: 
  x: 4
  y: 1
  z: 2
orientation: 
  x: 3
  y: 4
  z: 5
  w: 6, 4, 4.1, genpy.Time[1440510074253762006], genpy.Time[1440510278253762006]]

+ []
- [['h_1',
-   'test_task_1',
-   'oh what a lovely number 4 is',
-   position: 
-   x: 4
-   y: 1
-   z: 2
- orientation: 
-   x: 3
-   y: 4
-   z: 5
-   w: 6,
-   4,
-   4.1,
```

Also there is this:

```
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/mongodb_store/message_store_node.py", line 236, in <module>
    store = MessageStore()
  File "/opt/ros/indigo/lib/mongodb_store/message_store_node.py", line 26, in __init__
    db_host = rospy.get_param('mongodb_host')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 460, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msproxy.py", line 123, in __getitem__
    raise KeyError(key)
KeyError: 'mongodb_host'
```

So seems the message store doesn't work properly anymore... I think [this commit](https://github.com/strands-project/mongodb_store/commit/50cb1fb3d74416f415d55e6a95032594b48adfb9) might be to blame where the launch file has changes. Seems any tests using the mongodb test_mode won't work with the currently released version?

**Comment by marc-hanheide** [comment]
as this is a mongodb_store problem, please look and open an issue if you can confirm this. I'm happy for this to be merged.

**Comment by hawesie** [comment]
ok

**Pull request merged**
