### PR TITLE
Gcal routine

### PR DESCRIPTION
**Pull request by marc-hanheide**
try again on this branch (originally #131)

### CODE REVIEW

**Comment by marc-hanheide** [comment]
What was said about #131 also applies here:

> I open this addressing #130 already now, even though further additions will be made, but I want jenkins to test it. Don't merge until it is properly tested with the real scheduler and other routines.

**Comment by marc-hanheide** [comment]
OK, good, so all the unit tests work already. good, good...

**Comment by marc-hanheide** [comment]
Since I added a README, I think this is ready for a first "field test", so we might merge it soon. Testing in the context of other routines makes most sense once we have priorities, IMO.

**Comment by marc-hanheide** [comment]
@hawesie please merge if you deem ok

**Comment by hawesie** [comment]
Sorry to be a pain in the ass, but I think package should live in https://github.com/strands-project/strands_executive_behaviours not here.

**Comment by marc-hanheide** [comment]
I never got that differentiation quite right, I think. I thought https://github.com/strands-project/strands_executive_behaviours hosts specific behaviours for specific situations, while this is more a framework think. But if you want it there, I have no problem moving it there.

**Comment by hawesie** [comment]
On second thoughts I'm not so sure. routine_behaviours is separate because it has robot- and project-specific dependencies (mainly the battery level stuff), which this repo doesn't. As the gcal stuff doesn't have such dependencies, then it fits in fine here. Ignore me (deliverable writing and ale don't mix...).

**Comment by marc-hanheide** [comment]
Ah, moved it already... it's currently also imported here: https://github.com/strands-project/strands_executive_behaviours/tree/gcal_import_branch

So, your call!

**Comment by hawesie** [comment]
This code looks nice. My only worry is how the gcal-based task interact with the constraints imposed by the routine behaviours. Currently [RobotRoutine](http://strands-project.github.io/strands_executive_behaviours/routine_behaviours/html/classroutine__behaviours_1_1robot__routine_1_1RobotRoutine.html) prevents tasks from being sent when the battery is low and also when the "working hours" of the robot are complete (i.e. when it's locked in a cupboard). I'm a little nervous about how users can use gcal (perhaps by accident) to generate behaviour that is ultimately undesirable (i.e. drains battery or happens during the night). I guess hooking your task_allowed method to the RobotRoutine might provide a way to fix this.

**Comment by marc-hanheide** [comment]
Yes, this would have to be specialised in an specific implementation. Or, preferably probably, we can sort this with the priorities. I expect a "blocking routine" to schedule night time charge etc...

**Comment by marc-hanheide** [comment]
You're now also an admin for the default Henry calendar, if you want to test things.

**Comment by hawesie** [comment]
This can't be fixed with priorities as priorities change ordering, but ordering is not the problem, existence is. I am happy to merge this here, with the specific implementation which prevents tasks on low battery. added to routine_behaviours (or at least that repo).

**Pull request merged**
