### PR TITLE
Versions of scheduling algorithm can be chosen now + logging of results 

### PR DESCRIPTION
**Pull request by mudrole1**
When calling scheduler.solve(int, string) two parameters are needed now:
First is integer from <1,4> choosing the version of algorithm (1 original BC, 2 mine general, 3 old version of my specific code, 4 the newest version of mine specific).
The second is the name of file, where to save data.

### CODE REVIEW

**Comment by kunzel** [comment]
@mudrole1, it would be interesting to know why we want to choose one of the specific options. That is, what are the differences of the algorithms. Is anyone suited for a particular situation etc?

**Comment by hawesie** [comment]
This doesn't compile for me on OS X. Any clues?

```
/Users/nah/code/hydro_ws/src/strands_executive/scheduler/src/scipUser.cpp:343:9: error: no viable overloaded '='
  start = std::chrono::high_resolution_clock::now();
  ~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/bin/../lib/c++/v1/chrono:750:29: note: candidate function (the implicit copy assignment operator) not
      viable: no known conversion from 'time_point<class std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' to 'const
      time_point<class std::__1::chrono::system_clock, duration<[...], ratio<[...], 1000000>>>' for 1st argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Library/Developer/CommandLineTools/usr/bin/../lib/c++/v1/chrono:750:29: note: candidate function (the implicit move assignment operator) not
      viable: no known conversion from 'time_point<class std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' to
      'time_point<class std::__1::chrono::system_clock, duration<[...], ratio<[...], 1000000>>>' for 1st argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Users/nah/code/hydro_ws/src/strands_executive/scheduler/src/scipUser.cpp:345:7: error: no viable overloaded '='
  end = std::chrono::high_resolution_clock::now();
  ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/bin/../lib/c++/v1/chrono:750:29: note: candidate function (the implicit copy assignment operator) not
      viable: no known conversion from 'time_point<class std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' to 'const
      time_point<class std::__1::chrono::system_clock, duration<[...], ratio<[...], 1000000>>>' for 1st argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Library/Developer/CommandLineTools/usr/bin/../lib/c++/v1/chrono:750:29: note: candidate function (the implicit move assignment operator) not
      viable: no known conversion from 'time_point<class std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' to
      'time_point<class std::__1::chrono::system_clock, duration<[...], ratio<[...], 1000000>>>' for 1st argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
2 errors generated.

```

**Comment by mudrole1** [comment]
@hawesie What kind of c++ standard are you using for compilation? I am using c+11 and it might be the problem that c++98 doesnt support this time measurement. I can change it.

**Comment by hawesie** [comment]
@mudrole1 I am using c++11 as it is required for other scheduler parts you use.

**Comment by hawesie** [comment]
Seems that this needed instead

``` cpp
  std::chrono::high_resolution_clock::time_point start, end;
```

**Comment by hawesie** [comment]
Also pairs.cpp needs to be in the library

```
add_library(scheduler src/task.cpp src/scheduler.cpp src/distWrapper.cpp src/scipUser.cpp src/pairs.cpp)
```

**Comment by hawesie** [comment]
Please can you also update scheduler_node with the correct call to `solve`?

**Comment by hawesie** [comment]
I will change the scheduler call to include a filename option, but if it's an empty string can you skip the file saving?

**Comment by mudrole1** [comment]
Sure, I can do that. But I am still confused how can I pass some specific argument in the node

**Comment by hawesie** [comment]
Please just assume that there is a `string filename` variable in `getSchedule` and I will provide that either via a private parameter for the node or via the ros service call.

**Comment by mudrole1** [comment]
Also parameter `int version` is needed in `getSchedule` method now. If version is not a number from interval [1,4], I explicitly choose to call "mine specific algorithm"

**Comment by hawesie** [comment]
Ok!

**Comment by mudrole1** [comment]
@kunzel The option to choose a version of the scheduling algorithm is there mainly for testing of mine proposed changes to original Brian Coltin's algorithm. The versions mainly differ in following way: Brian Coltin's original work (1) is general approach, which might take a lot of time during searching for the best optimization criteria. Mine general approach (2) contains deeper discussion of overlapping intervals (extends Coltin's work) and doesnt add 2 constraints, (add only one), when it makes no sense to add both. Moreover, this solution is still general and should not affect the optimal criteria. However, it seems that it doesnt speed up the search to much in general cases. The version (3) and (4) are more specific in the sense that they pushed the search by adding a constraint, which is more logical. This might lead to loosing optimal solution, although it speed up the search. The version (3) was run on Bob, the version (4) is the newest and it takes into account the distance between tasks, which version (3) didnt use. To conclude, we would like to use version (2) (search can be long for big domains) or mainly (4). They dont differ for some specific configurations of tasks. I hope this make sense.

**Comment by hawesie** [comment]
We'll talk coding standards later, but I will merge for now ;)

**Pull request merged**
