### PR TITLE
Consider navigation time when deciding when to execute tasks.

### PR DESCRIPTION
**Pull request by hawesie**
This PR updates the task executor to ensure navigation happens prior to the opening of the task execution window (`task.start_after`) rather than considering that the window indicated the start of the navigation time. There is a new test to verify this. a1be3ee adds the logic, the other commits are testing code.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@cdondrup  can we please test this branch in the tests you're doing?

**Comment by marc-hanheide** [comment]
@hawesie, if the robot arrives early, I.e. prior to start_after what will it do? Waiting doing nothing or start the task? Because it will look odd if it just sits there not doing anything. At least it should be configurable I'd argue, e.g. having a flag `start_on_arrival` in the `Task` or something.

**Comment by hawesie** [comment]
At the moment there is no check on arrival at all. I could add one, but I would suggest leaving it until after the deployment as it would be much more structural change than this one.

**Comment by marc-hanheide** [comment]
Sorry, don't understand. What do you mean there is no check on arrival? Does that mean it simply runs the task once it arrives, because it doesn't check again?

**Comment by hawesie** [comment]
There is currently no check on arrival. Once navigation to a task starts, the task execution always follows the navigation if navigation reports success. There is no check on time between navigation and task execution.

**Comment by marc-hanheide** [comment]
good enough for me for now.

**Comment by hawesie** [comment]
Oops, added an extra commit by mistake. Will remove it.

**Comment by hawesie** [comment]
@bfalacerda @marc-hanheide can this be merged? has it been tested in anger? I've been running it a lot locally in sim.

**Comment by bfalacerda** [comment]
this doesnt break anything, but i cant say if bob is starting to navigate when he should. There's only 3 tasks per day where that is checkable, and I was never looking at it to see.

I'll try do do it tomorrow

**Comment by marc-hanheide** [comment]
If it didn't break I'm :+1: for merge. We have many scheduled tasks and should be able to see quickly.

**Comment by bfalacerda** [comment]
i just saw this working as it should.

**Pull request merged**
