### PR TITLE
Dealing with case where task added for scheduling has no start node.

### PR DESCRIPTION
**Pull request by hawesie**
Tested in simulation and works here.

### CODE REVIEW

**Comment by hawesie** [comment]
@cburbridge @bfalacerda the last commit adds the ability you requested today. More PRs for this coming in other repos.

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
@marc-hanheide seems to be the gcal test? https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-strands_executive/70/testReport/

**Comment by marc-hanheide** [comment]
Seems to be unrelated. Problem seems to be that in that test the mongodb_store doesn't come up:

```
[ERROR] [WallTime: 1429471297.291623] Sun Apr 19 19:21:37.291 [initandlisten] ERROR: listen(): bind() failed errno:98 Address already in use for socket: 0.0.0.0:56871
[ERROR] [WallTime: 1429471297.292038] Sun Apr 19 19:21:37.291 [initandlisten] ERROR:   addr already in use
[ERROR] [WallTime: 1429471297.297459] MongoDB process stopped!
[ERROR] [WallTime: 1429471297.298517] Mongo process error! Exit code=48
```

So I think this is was more or less bad luck when trying to guess ports for mongodb?

**Pull request merged**
