### PR TITLE
subscribe to topological map topic, and update MDP structure when a …

### PR DESCRIPTION
**Pull request by bfalacerda**
…new topo map is published

Addresses my part of https://github.com/strands-project/aaf_deployment/issues/358. Tested by restarting topological navigation with different topo map arguments

### CODE REVIEW

**Comment by bfalacerda** [comment]
retest this please

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
@marc-hanheide are these tests failing due to some jenkins problem?

**Comment by marc-hanheide** [comment]
No, some Class is not available during tests, right:

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pr-indigo-strands_executive/monitored_vcs/task_executor/scripts/mdp_task_executor.py", line 7, in <module>
    from strands_executive_msgs.srv import GetGuaranteesForCoSafeTask, GetGuaranteesForCoSafeTaskRequest, AddCoSafeTasks
ImportError: cannot import name AddCoSafeTasks
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/pr-indigo-strands_executiBuild timed out (after 120 minutes). Marking the build as aborted.
```

**Comment by bfalacerda** [comment]
but the file is there, and in CMakeLists:

https://github.com/strands-project/strands_executive/pull/264/commits/d99f21b54bf6d5ab318466a1da2738d10eea1ae7

**Comment by hawesie** [comment]
@marc-hanheide yeah, I can't see a problem with our code for this.

**Comment by marc-hanheide** [comment]
OK, to be honest, I have been spending 30 minutes now and can't understand. It seems to be using an installed package rather than the local one. Most likely something to do with the `package.xml` and the `test_depend` stuff. But I really don't understand what is going on here... Jenkins is fine. This is something with the setup of the tests.

**Pull request merged**
