### PR TITLE
Improved mine version of the scheduler. Moreover, only version 1 (Brian Coltin's) and 4(mine) are available now.

### PR DESCRIPTION
**Pull request by mudrole1**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
`python-dateutils` is not an acceptable rosdep key. If none exists and you need it then please add one in https://github.com/strands-project/rosdistro/blob/strands-devel/rosdep/strands.yaml (file a pull request with the addition)

**Comment by marc-hanheide** [comment]
or is this very outdated @hawesie ?

**Comment by hawesie** [comment]
No, this is new. 

@mudrole1 I am adding the rosdep now.

**Comment by hawesie** [comment]
python-dateutil pr https://github.com/ros/rosdistro/pull/6123

**Comment by hawesie** [comment]
dateutil now in.

**Comment by hawesie** [comment]
It won't build without topological nav, so I will merge in anyway (as this branch is not released anyway).

**Pull request merged**
