### PR TITLE
Fix for #163.

### PR DESCRIPTION
**Pull request by hawesie**

### CODE REVIEW

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
I guess that last commit doesn't work. Needs more work.

**Comment by hawesie** [comment]
retest this please

**Comment by marc-hanheide** [comment]
Again... Your fifo test is brittle

**Comment by hawesie** [comment]
@marc-hanheide it's your fault.. somehow. :scream_cat:

**Comment by hawesie** [comment]
retest this please

**Comment by hawesie** [comment]
Actually the change I made to fix this seems to have made it less stable!

**Comment by marc-hanheide** [comment]
Very pragmatic solution indeed

**Pull request merged**
