### PR TITLE
Gcal tools add description to yaml instead of processing separately

### PR DESCRIPTION
**Pull request by heuristicus**
Needed as part of strands-project/g4s_deployment#204

### CODE REVIEW

**Comment by hawesie** [comment]
@marc-hanheide please confirm this is ok for you

**Review by marc-hanheide — COMMENTED** [review]
This assumes that the factories can deal with the yaml and treat it. I don't think most of ours actually do. Needs very careful checking in various places. Can we add a check that the values are properly populated by the factory and if not still set them?

**Comment by marc-hanheide** [comment]
Actually, ignore my previous comment... it should actually work, IF the factories are correctly implemented, e.g., if the call the `super.create()` method. They should, but I'm not sure they all do. I guess we'll have to try...

**Comment by heuristicus** [comment]
Is this ok to merge, in that case?

**Comment by marc-hanheide** [comment]
Ok for me

**Pull request merged**
