### PR TITLE
Gcal routine

### PR DESCRIPTION
**Pull request by marc-hanheide**
I open this addressing #130 already now, even though further additions will be made, but I want jenkins to test it. Don't merge until it is properly tested with the real scheduler and other routines.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Aargh, @hawesie, can we fix this problem please? This fails because of prism and doesn't reach my unit test. What is wrong?

**Comment by bfalacerda** [comment]
@marc-hanheide you need to merge into `hydro-release`

**Comment by marc-hanheide** [comment]
But that would then not be build be jenkins... Shall I change the rosdistro config to make hydro-release the official branch for PRs? I understand, w'll need to resolve the prism issue soon anyway, right?

**Comment by bfalacerda** [comment]
I thought that the branch Jenkins was testing was hydro-release..

Anyway, I'm currently focused on getting everything released again, it should be done no later than Wednesday

**Comment by hawesie** [comment]
@marc-hanheide everything we do now is `hydro-release`. The `hydro-devel` branch has never built successfully on @strands-jenkins.

**Comment by marc-hanheide** [comment]
OK. So shall I switch to that branch for Jenkins too?

**Comment by marc-hanheide** [comment]
OK, to be re-opened for other branch

**Comment by hawesie** [comment]
> On 15 Mar 2015, at 13:02, Marc Hanheide notifications@github.com wrote:
> 
> OK. So shall I switch to that branch for Jenkins too?

Yes please!

**Pull request closed without merging**
