### PR TITLE
more robust calls to /topological_prediction/predict_edges service.

### PR DESCRIPTION
**Pull request by bfalacerda**
mitigates https://github.com/strands-project/strands_executive/issues/206

Catches ServiceException, prints out warnings, and provides expected nav times for the last epoch requested.

### CODE REVIEW

**Comment by bfalacerda** [comment]
retest this please

**Comment by bfalacerda** [comment]
why!? :(

**Comment by bfalacerda** [comment]
i guess the test wants the service to fail? @hawesie

**Comment by hawesie** [comment]
Ignore the FIFO tester. I've added some new testing in the new executor which will replace that.

**Comment by bfalacerda** [comment]
can i merge then?

**Pull request merged**
