### PR TITLE
Expected duration + task ids

### PR DESCRIPTION
**Pull request by hawesie**
This adds the functionality to serve task ids to other components so that the routine add_tasks can return real ids too.

Also adds expected duration to the task definition.

### CODE REVIEW

**Comment by hawesie** [comment]
@bfalacerda please test with your code.

**Comment by bfalacerda** [comment]
@hawesie this is missing the definition for ``GetIDs.srv``

**Comment by hawesie** [comment]
Oops, added.

**Comment by bfalacerda** [comment]
i still get an empty response from the service call

**Comment by hawesie** [comment]
Have you also used this https://github.com/strands-project/strands_executive_behaviours/pull/31

**Pull request merged**
