### PR TITLE
cope with negative travel expectations

### PR DESCRIPTION
**Pull request by bfalacerda**

### CODE REVIEW

**Comment by hawesie** [comment]
Can you add some default value for negative edges? If not we might end up with odd behaviours.

**Comment by bfalacerda** [comment]
as is, it "defaults" to the last prediction that wasn't negative

**Comment by hawesie** [comment]
Ok.

**Comment by hawesie** [comment]
See tmux. It doesn't seem to have worked.

**Comment by hawesie** [comment]
Note that this was the first task after a restart (so the prior default may not have worked).

**Pull request merged**
