### PR TITLE
[gcal_routine] Gcal priorities

### PR DESCRIPTION
**Pull request by marc-hanheide**
added support for task priorities of gcal_routine

### CODE REVIEW

**Comment by marc-hanheide** [comment]
closes https://github.com/strands-project/aaf_deployment/issues/107

**Comment by marc-hanheide** [comment]
@cdondrup this is what you might have been waiting for

**Comment by cdondrup** [comment]
When will this actually set the prio to `2`? I.e., before or after the `create` function is called?

**Comment by marc-hanheide** [comment]
After. It will overwrite them. Because the routine should ultimately decide the priority.

**Comment by cdondrup** [comment]
But won't this always be 2 then? this basically means that every task assigned by the calendar has prio 2 and therefore if the walking group and bellbot would overlap the scheduler would throw away what ever task came last? I guess that won't be a problem but then it also doesn't matter what prio I assign in the text field in the calendar event? Or is that even possible?

**Comment by marc-hanheide** [comment]
We could later add to use the colours in gcal to represent them

**Comment by cdondrup** [comment]
OK, I'll have to live with not being more important then ;)

**Comment by marc-hanheide** [comment]
Yes, right now all would be 2 but that's not important as we won't put them in overlapping will we?

**Comment by cdondrup** [comment]
We better don't.
But I see the argument behind this, yes.

**Pull request merged**
